### ISSUE TITLE
move to https://github.com/JOSM/

### ISSUE THREAD

**Issue by Rub21** [mapbox/JOSM-configuration#27]
@aarthykc  , maybe  we can move this plugin to https://github.com/JOSM/  as [to-fix](https://github.com/JOSM/tofix-plugin/).  the advantage is that the main developers of JOSM give support for plugin when something change in JOSM. check the history of to-fix: https://github.com/JOSM/tofix-plugin/commits/master

cc. @geohacker @maning @planemad

**Comment by planemad** [comment]
👍

**Comment by geohacker** [comment]
@Rub21 great idea!

**Comment by aarthykc** [comment]
@Rub21 makes sense, could you help me set this up?

**Comment by don-vip** [comment]
Hello,
I have created #28 as the plugin does not work with latest versions of JOSM.
Can you please merge it, or transfer the repo to the JOSM organization if you don't plant to maintain the plugin?
You can look at Github documentation: https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/#transferring-to-another-organization

**Comment by don-vip** [comment]
Switch done.
